// src/App.tsx
import { BrowserRouter as Router , Routes, Route, Navigate} from 'react-router-dom'
import './App.scss'
import ConfigPage from './pages/config/config'
import Sumadora from './pages/sumadora/sumadora'

function App() {
  return (
    <div className="App">
      <Router>
        <Routes>          
          <Route path='' element={<Sumadora/>} />
          <Route path='config' element={<ConfigPage/>} />
          <Route path='*' element={<Navigate to='' replace />} />
        </Routes>
      </Router>
    </div>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import { Router, Route} from "svelte-navigator";	
    import SumadoraPage from "./lib/pages/SumadoraPage.svelte";
    import ConfigPage from "./lib/pages/ConfigPage.svelte";
</script>

<Router>
  <Route path="/" primary={false} component={SumadoraPage}/>
  <Route path="/config" primary={false} component={ConfigPage}/>
</Router>

<style>
  
</style>
